// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_scan_baumgartner
Rcpp::List cpp_scan_baumgartner(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d);
RcppExport SEXP _npwbs_cpp_scan_baumgartner(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_baumgartner(x, starts, ends, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scan_cvm
Rcpp::List cpp_scan_cvm(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d);
RcppExport SEXP _npwbs_cpp_scan_cvm(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_cvm(x, starts, ends, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scan_lepage
Rcpp::List cpp_scan_lepage(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d);
RcppExport SEXP _npwbs_cpp_scan_lepage(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_lepage(x, starts, ends, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scan_mood
Rcpp::List cpp_scan_mood(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d);
RcppExport SEXP _npwbs_cpp_scan_mood(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_mood(x, starts, ends, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scan_mw
Rcpp::List cpp_scan_mw(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d);
RcppExport SEXP _npwbs_cpp_scan_mw(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_mw(x, starts, ends, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scan_zhang
Rcpp::List cpp_scan_zhang(Rcpp::NumericVector x, Rcpp::IntegerVector starts, Rcpp::IntegerVector ends, int d, Rcpp::List bundled, Rcpp::Nullable<Rcpp::List> extended);
RcppExport SEXP _npwbs_cpp_scan_zhang(SEXP xSEXP, SEXP startsSEXP, SEXP endsSEXP, SEXP dSEXP, SEXP bundledSEXP, SEXP extendedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type bundled(bundledSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type extended(extendedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scan_zhang(x, starts, ends, d, bundled, extended));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_npwbs_cpp_scan_baumgartner", (DL_FUNC) &_npwbs_cpp_scan_baumgartner, 4},
    {"_npwbs_cpp_scan_cvm", (DL_FUNC) &_npwbs_cpp_scan_cvm, 4},
    {"_npwbs_cpp_scan_lepage", (DL_FUNC) &_npwbs_cpp_scan_lepage, 4},
    {"_npwbs_cpp_scan_mood", (DL_FUNC) &_npwbs_cpp_scan_mood, 4},
    {"_npwbs_cpp_scan_mw", (DL_FUNC) &_npwbs_cpp_scan_mw, 4},
    {"_npwbs_cpp_scan_zhang", (DL_FUNC) &_npwbs_cpp_scan_zhang, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_npwbs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
