# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_scan_anderson_darling <- function(x, starts, ends, d = 2L) {
    .Call(`_npwbs_cpp_scan_anderson_darling`, x, starts, ends, d)
}

cpp_scan_baumgartner <- function(x, starts, ends, d = 2L) {
    .Call(`_npwbs_cpp_scan_baumgartner`, x, starts, ends, d)
}

cpp_scan_cvm <- function(x, starts, ends, d = 2L) {
    .Call(`_npwbs_cpp_scan_cvm`, x, starts, ends, d)
}

cpp_scan_lepage <- function(x, starts, ends, d = 2L, combination = "sum") {
    .Call(`_npwbs_cpp_scan_lepage`, x, starts, ends, d, combination)
}

cpp_scan_mood <- function(x, starts, ends, d = 2L) {
    .Call(`_npwbs_cpp_scan_mood`, x, starts, ends, d)
}

cpp_scan_mw <- function(x, starts, ends, d = 2L) {
    .Call(`_npwbs_cpp_scan_mw`, x, starts, ends, d)
}

cpp_scan_zhang <- function(x, starts, ends, d, bundled, extended = NULL) {
    .Call(`_npwbs_cpp_scan_zhang`, x, starts, ends, d, bundled, extended)
}

